# Generated by Django 3.1.1 on 2020-12-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence_text', models.CharField(max_length=300)),
                ('sentence_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='languages.languages')),
            ],
        ),
    ]
