# Generated by Django 3.1.1 on 2020-09-22 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('sentences', '0002_auto_20200918_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentences',
            name='sentence_lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='languages.languages'),
        ),
    ]
