# Generated by Django 3.1.1 on 2020-09-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('lang_id', models.AutoField(primary_key=True, serialize=False)),
                ('lang_code', models.CharField(max_length=3, unique=True)),
                ('lang_name', models.CharField(max_length=100)),
                ('lang_type', models.CharField(choices=[('local', 'local'), ('foreign', 'foreign')], default='foreign', max_length=100)),
            ],
        ),
    ]
