# Generated by Django 3.1.1 on 2020-12-29 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import translations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sentences', '0001_initial'),
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('translation_id', models.AutoField(primary_key=True, serialize=False)),
                ('audiofile', models.FileField(null=True, upload_to=translations.models.translation_directory_path)),
                ('recorded_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sentences.sentences')),
                ('target_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.languages')),
            ],
        ),
    ]
