# Generated by Django 3.1.1 on 2020-09-30 19:44

from django.db import migrations, models
import translations.models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='audiofile',
            field=models.FileField(null=True, upload_to=translations.models.translation_directory_path),
        ),
    ]
