# Generated by Django 3.1.1 on 2020-11-10 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0003_auto_20200922_2349'),
        ('translations', '0002_auto_20200930_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sentences.sentences'),
        ),
    ]
